name: klypt
description: Klypt - Offline, encrypted password manager built with Flutter.
publish_to: 'none'
version: 1.5.4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  local_auth: ^2.1.6
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  cryptography: ^2.7.0
  intl: ^0.20.2
  uuid: ^4.0.0
  equatable: ^2.0.8
  share_plus: ^12.0.1
  file_picker: ^10.3.10
  lucide_icons: ^0.257.0
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.0
  http: ^1.2.0
  package_info_plus: ^9.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/branding/logo5.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0B0F1A"
  adaptive_icon_foreground: "assets/branding/logo5.png"
  adaptive_icon_monochrome: "assets/branding/logo3.png"

flutter_native_splash:
  color: "#0B0F1A"
  image: assets/branding/logo5.png
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/branding/
